# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'


- script: |
    npm install
  displayName: 'npm install' 
  
- script: | 
    npm install -g @angular/cli@12.0.0
  displayName: 'install angular cli' 

- script: | 
    node node_modules/protractor/bin/webdriver-manager update --standalone
    sudo apt-get -qq -y update
    sudo apt-get -qq -y install xvfb libgtk2.0-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2
  displayName: 'install webdriver manager' 

- script: |
    ng e2e 
  displayName: 'run tests' 
- task: Docker@2
  inputs:
    containerRegistry: 'nwtaJamgroup'
    repository: 'angular'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
 
 
