
trigger:
- master

pool:
  vmImage: windows-latest

stages:
  - stage: Build
    jobs:
      - job: Frontend
        steps:
        - task: NodeTool@0
          inputs:
            versionSpec: '10.x'
          displayName: 'Install Node.js'
          
        - script: |
            npm install
          displayName: 'npm install and build' 
          
        - script: | 
            npm install -g @angular/cli 
          displayName: 'install angular cli' 

        - script: | 
            npx webdriver-manager update 
          displayName: 'install webdriver manager' 

        - script: |
            ng e2e --webdriver-update=false
          displayName: 'run tests' 

 
